// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dzeikksxqwbafbsdbviv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6ZWlra3N4cXdiYWZic2Ridml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjIxNzcsImV4cCI6MjA2NzIzODE3N30.db9i3ypQ-i22aHVKdKnKuvPTvZD5UyZNqBxu0k7arx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);